version: '3.8'
services:

  db:
    image: postgres:11.1
    volumes:
      - /var/lib/postgresql/data/
    container_name: animals-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_URL}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # - TZ=Europe/Moscow