spring:
  application.name: education-project
  main:
    allow-bean-definition-overriding: true

application:
  scheduled:
    time: 60000

dog:
  names: barsik,persik,dushka,mushka,tuzik,taratuwka,bumburuwka,rizik, pesik, piksel, smelchak,wustrik,seriy,beliy,oskal,tigr,vozak, poned, vtorn, sred, chetv
wolf:
  names: smelchak,wustrik,seriy,beliy,oskal,tigr,vozak, poned, vtorn, sred, chetv, barsik,persik,dushka,mushka,tuzik,taratuwka,bumburuwka,rizik, pesik, piksel