spring:
  application.name: education-project
  main:
    allow-bean-definition-overriding: true
#  flyway:
#    locations: classpath:migrations
#    url: jdbc:postgresql://localhost:5432/animals
#    user: postgres
#    password: iamroot
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: jdbc:postgresql://localhost:5432/animals
    username: postgres
    password: iamroot
#  jpa:
#    hibernate:
#      ddl-auto: create-drop


application:
  scheduled:
    time: 60000
  scheduledDB:
    time: 15000
duplicate:
  time: 10000
average:
  time: 20000

animal:
  names: Warik,Seriy, Piksel
  age: 5,10,15
  animaltype: Dog, Wolf, Cat
  isWild: true, false
  breed: puwistii, korotkowertii, srednii
  cost: 500, 1000, 1500
  dates: 1983-03-15, 1984-07-22

dog:
  names:
    random: barsikRandom,persikRandom
    nerandom: pesik, piksel
  breeds: bolwoi, malenkiy
  prices: 1500, 3000
  characters: veseliy, smeliy
  dates: 1983-03-15, 1984-07-22

wolf:
  names:
    random: smelchakRandom,wustrikRandom
    nerandom: seriy,beliy
  breeds: bolwoi, malenkiy
  prices: 1500, 3000
  characters: dobriy, silniy
  dates: 1983-03-15, 1984-07-22

logging:
  level:
    root: INFO
  #    org.springframework.web: DEBUG
  #    org.hibernate: ERROR
  file:
    name: ./logs/app.log
    logrotate:
      max-history: 10
      max-size: 10MB
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %-5level - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"