create table animal_type
(
    id_type integer generated by default as identity
            constraint animal_type_pk primary key,
    type    char(50) not null,
    is_wild boolean not null,
    created timestamp with time zone default CURRENT_TIMESTAMP not null,
    updated timestamp with time zone  default CURRENT_TIMESTAMP
);

CREATE SEQUENCE animal_type_id_type_seq START WITH 1 INCREMENT BY 1;
alter sequence animal_type_id_type_seq owned by animal_type.id_type;